SET GLOBAL suffix_normalization=OFF;
SET GLOBAL suffix_unicode_version="DEFAULT";

DROP TABLE IF EXISTS su ;
CREATE TABLE su (a TEXT, FULLTEXT(a) WITH PARSER suffix) CHARSET latin1;
INSERT INTO su VALUES ("abcde");
INSERT INTO su VALUES ("dummy");
INSERT INTO su VALUES ("dummyde");
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('abcde');
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('ab' IN BOOLEAN MODE);
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('+ab' IN BOOLEAN MODE);
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('+de -du' IN BOOLEAN MODE);
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('+abc' IN BOOLEAN MODE);
DROP TABLE IF EXISTS su ;

DROP TABLE IF EXISTS su ;
CREATE TABLE su (a TEXT, FULLTEXT(a) WITH PARSER suffix) CHARSET utf8 COLLATE utf8_general_ci;
INSERT INTO su VALUES ("ﾃｽﾄ");
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('テスト' IN BOOLEAN MODE);
DROP TABLE IF EXISTS su ;

SET GLOBAL suffix_normalization="KD";
DROP TABLE IF EXISTS su ;
CREATE TABLE su (a TEXT, FULLTEXT(a) WITH PARSER suffix) CHARSET utf8 COLLATE utf8_general_ci;
INSERT INTO su VALUES ("ﾃｽﾄ");
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('テスト' IN BOOLEAN MODE);
SELECT COUNT(*) FROM su WHERE MATCH(a) AGAINST('デズド' IN BOOLEAN MODE);
DROP TABLE IF EXISTS su ;

SET GLOBAL suffix_normalization=OFF;
SET GLOBAL suffix_unicode_version="DEFAULT";
